# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.boot_timeout = 900

  # Master
  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    master.vm.hostname = "master.example.com"
    #master.vm.network "private_network", ip: "172.42.42.100"
    master.vm.network :public_network, bridge: 'VagrantMaster'
    master.vm.provider "hyperv" do |v|
      v.vmname = "master"
      v.memory = 2048
      v.cpus = 2
      v.ip_address_timeout = 600
    end
    master.vm.provision "shell", path: "bootstrap_master.sh"
  end

  NodeCount = 2

  # Nodes
  (1..NodeCount).each do |i|
    config.vm.define "worker#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "workernode#{i}.example.com"
      workernode.vm.network :public_network, bridge: 'VagrantMaster' 
      workernode.vm.provider "hyperv" do |v|
        v.vmname = "workernode#{i}"
        v.memory = 1024
        v.cpus = 1
        v.ip_address_timeout = 600
      end
      #workernode.vm.provision "shell", path: "bootstrap_nodes.sh"
    end
  end

end