version: '3'

services:

  api:
    #TODO: Consider building and pushing the image to GitLab registry!
    image: edo-api:latest
    ports:
      - 1234
    environment:
      - SERVICE_PORTS=1234  
    depends_on:
      - db      
    volumes:
    - ./logs:/var/log

  lb:
    image: dockercloud/haproxy
    depends_on:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9090:80

  #TODO: Consider adding container for PGAdmin for easy management of the DB locally    
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: edo-api
    ports:
      - "5432:5432"  
    volumes:
      - ./postgres/pg-data:/var/lib/postgresql/data
      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql